"""fix

Revision ID: f09ce86daeab
Revises: a9a2991fdaf9
Create Date: 2024-12-04 14:28:06.749598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'f09ce86daeab'
down_revision = 'a9a2991fdaf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('command_hashes')
    op.drop_table('permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('target_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('target_id', sa.BIGINT(), nullable=False),
    sa.Column('guild_id', sa.BIGINT(), nullable=False),
    sa.Column('permission_type', sa.VARCHAR(length=5), nullable=True),
    sa.Column('can_use_bot', sa.BOOLEAN(), nullable=True),
    sa.Column('can_manage_permissions', sa.BOOLEAN(), nullable=True),
    sa.Column('can_use_admin_commands', sa.BOOLEAN(), nullable=True),
    sa.Column('max_requests_per_day', sa.INTEGER(), nullable=True),
    sa.Column('view_channel', sa.BOOLEAN(), nullable=True),
    sa.Column('manage_channels', sa.BOOLEAN(), nullable=True),
    sa.Column('manage_roles', sa.BOOLEAN(), nullable=True),
    sa.Column('manage_messages', sa.BOOLEAN(), nullable=True),
    sa.Column('send_messages', sa.BOOLEAN(), nullable=True),
    sa.Column('send_messages_in_threads', sa.BOOLEAN(), nullable=True),
    sa.Column('create_public_threads', sa.BOOLEAN(), nullable=True),
    sa.Column('create_private_threads', sa.BOOLEAN(), nullable=True),
    sa.Column('attach_files', sa.BOOLEAN(), nullable=True),
    sa.Column('add_reactions', sa.BOOLEAN(), nullable=True),
    sa.Column('use_external_emojis', sa.BOOLEAN(), nullable=True),
    sa.Column('use_external_stickers', sa.BOOLEAN(), nullable=True),
    sa.Column('mention_everyone', sa.BOOLEAN(), nullable=True),
    sa.Column('manage_webhooks', sa.BOOLEAN(), nullable=True),
    sa.Column('moderate_members', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_hashes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('guild_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('command_hash', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('discord_id', sa.BIGINT(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    # ### end Alembic commands ###