"""command2

Revision ID: a9a2991fdaf9
Revises: 01230bac67c2
Create Date: 2024-12-04 04:47:34.453058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'a9a2991fdaf9'
down_revision = '01230bac67c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###