"""initial

Revision ID: ec6c27179e59
Revises: 
Create Date: 2024-12-04 22:09:31.185298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'ec6c27179e59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###